module.exports = {}
module.exports.Widget = require './apex-widget'
module.exports.Button = require './apex-button'
module.exports.Input = require './apex-input'
module.exports.TextEditor = require './apex-text-editor'
module.exports.TreeView = require './apex-tree-view'
module.exports.ListView = require './apex-list-view'
module.exports.Label = require './apex-label'
module.exports.ButtonGroup = require './apex-button-group'
module.exports.CheckBox = require './apex-checkbox'
module.exports.LoadingSpinner = require './apex-loading-spinner'
window.Apex?.Widgets = module.exports
